#!/bin/bash

APP="$1"
IMAGE="dokku/$APP"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -e
echo "-----> Injecting ØMQ ..."
ZMQ_VERSION=$(< "$DIR/zmq_version")
FILE_NAME="zeromq-$ZMQ_VERSION"
ZMQ_URL="http://download.zeromq.org/$FILE_NAME.tar.gz"
DST=/usr/local
COMMAND=$(cat <<EOF
    curl $ZMQ_URL | tar -xz &&
    cd $FILE_NAME &&
    ./configure --prefix=$DST &&
    make &&
    make install &&
    ldconfig &&
    cd .. &&
    rm -rf $FILE_NAME
EOF)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
