#!/bin/bash

APP="$1"
IMAGE="app/$APP"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -e
echo "-----> Injecting ØMQ ..."
ZMQ_VERSION=$(< "$DIR/zmq_version")
FILE_NAME="zeromq-$ZMQ_VERSION"
TARBALL="$FILE_NAME.tar.gz"
ZMQ_URL="http://download.zeromq.org/$TARBALL"
DST=/usr/local
COMMAND=$(cat <<EOF
wget $ZMQ_URL | tar -xf $TARBALL &&
rm -rf $TARBALL &&
cd $FILE_NAME &&
./configure --prefix=$DST &&
make &&
make install
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
